## 콜백

콜백 함수는 함수의 인자로 전달되는 함수를 말한다. 

```js
setTimeout(function() {
    console.log(1);
},1000);
```

위 코드는 우리가 자주 쓰는 콜백 함수다. 위에서 보면 알 수 있듯이 함수의 인자로 나중에 사용할 함수를 전달받아서 사용한다. 콜백 함수는 다른 함수와 다른 것이 없다. 콜백 함수는 다른 함수와 마찬가지로 똑같은 자바스크립트 함수이다. 일반적으로 콜백은 익명함수로 사용한다.

보통 콜백 함수를 사용하는 이유는 비동기적으로 코드를 작성해야 하는 상황이기 때문이다. setTimeout 함수도 비동기 함수의 예시이다. 비동기 함수의 특징을 잘 나타내는 코드를 보자.

```js
console.log('Before setTimeout()!');
function a() {
    console.log('callBack is done!');
}
setTimeout(a, 1000);
console.log('After setTimeout()!');
```

위 코드를 실행해보면 예상과 다른 결과가 나올 것이다. 우리는 일반적으로 순차적인 실행을 하는 코드에 익숙하다. 하지만 위 코드를 실행해보면 순차적으로 실행될 것 이라는 예상과 다르게 아래와 같이 출력된다.

![callback 함수 결과](./pictures/callback.png)

이렇게 순차적이지 않다는 것이 바로 비동기적 실행의 특징이다. 비동기적 실행의 장점은 한 구문을 실행하는 데 모든 자원을 사용하지 않는다는 것이다. 하고 있는 작업보다 먼저 처리할 수 있는 작업이 있다면 그 작업을 먼저 처리하는 방식은 비동기적 실행의 가장 좋은 점이다.

자바스크립트는 싱글 스레드를 사용하기 때문에, 60초 동안 대기하라는 코드를 동기적으로 실행하게 되면, 다른 코드들까지 저 동작을 위해 기다리게 되어 자원의 낭비가 발생하게 된다. 이런 현상은 UX적으로 매우 좋지 않은 상황이라고 할 수 있다. 하지만 비동기적 실행을 하게 된다면 이런 현상을 해결할 수 있다. 아래에 동기적 실행의 나쁜 예시를 보면 비동기적 실행의 필요성을 알 수 있다.

```js
console.log('Before Loading!');
function loading() {
    var b = 0;
    for(var a=0 ; a<5000000000 ; a++) {
        b++;
    }
    console.log('loading is done');
}
loading();
console.log('After Loading!');
```

보통 콜백 함수에 넘기는 함수는 이름이 없는 익명 함수를 사용한다.

## 스코프와 비동기적 실행

비동기적 실행에서 어려운 점은 스코프와 클로저가 비동기적 실행에 영향을 미치는 부분이다.함수를 호출하면 항상 `클로저`가 만들어진다. 매개변수를 포함한 함수내에서 생성된 변수는 모두 무언가가 자신에게 접근할 수 있는 한 `클로저`는 계속 존재한다.

아래 예제는 이전에 클로저 파트에서 봤었지만, 다시 한 번 countdown 함수에 대해서 생각해보자.

```js
function countdown() {
  let i;
  console.log('Count down!');
  for(i=5; i>=0; i--) {
    setTimeout(function() {
      console.log(i===0 ? "GO!" : i);
    }, (5-i)*1000);
  }
}
countdown();
```

위 코드의 동작을 보면 1초마다 -1이 6번 출력된다. 코드를 보면 5부터 카운트다운 할 것 같지만 실제로는 그렇지 않다. 이 예제는 원래 var을 통해서 변수 i를 선언해서 let을 통해서 변수를 선언하면 이 문제를 해결할 수 있었지만, 이 예제에서는 i를 for 루프 바깥에서 선언했으므로 똑같은 문제가 발생하게 된다.

이 문제가 발생하는 이유는 `countdown`이 호출될 때, 변수 i가 들어있는 클로저가 발생하게 된다. 이때, for 루프 안에서 만드는 콜백은 모두 i에 접근할 수 있는데, 각각의 콜백이 접근하는 i는 똑같은 i이다.

여기서 주의깊게 봐야 하는 부분은 for 루프안에서 i를 두 가지 방법으로 사용했다는 것이다. `setTimeout`의 콜백 함수에서 호출한 i와 `setTimeout`의 인자로 들어간 타임아웃을 계산하기 위한 i가 있다. 여기서 타임아웃을 계산할 때 사용된 i는 제대로 들어갔다.(첫 번째 타임아웃은 0, 두 번째 타임아웃은 1000, 세 번째 타임아웃은 2000...) 이 이유는 바로 `setTimeout`은 동기적으로 실행되기 때문이다. 비동기적인 부분은 `setTimeout`에 전달된 콜백 함수이다.

이 문제는 `즉시 호출 함수 표현식(IIFE)`으로 해결할 수 있고, i를 for 루프 안에서 선언하는 방식으로 해결할 수 있다.

```js
function countdown() {
  console.log('Count down!');
  for(let i=5; i>=0; i--) {
    setTimeout(function() {
      console.log(i===0 ? "GO!" : i);
    }, (5-i)*1000);
  }
}
countdown();
```

여기서 let을 for 루프 안에서 선언했을 때와 바깥에 선언했을 때 이 두 상황에서의 차이는 이렇게 말할 수 있다. 먼저 for 루프 바깥에서 i를 선언했을 때에는 setTimeout의 콜백 함수에서 참조하는 i는 for루프가 이미 다 끝난 상태의 i이다. 하지만 for 루프 안에서 선언된 i는 각각의 **루프**마다 **독립적인 스코프**를 가지기 때문에 콜백 함수는 **클로저**를 형성하게 된다. 따라서 콜백에서 쓰이는 i의 값은 매 루프에서 콜백이 실행될 때 마다 다를 수 있다.

## 콜백 헬

콜백을 사용해서 비동기 처리를 할 수 있지만, 여기에는 큰 문제가 하나있다. 한 번에 여러가지 작업을 기다려야 한다면 콜백들을 관리하기 까다로워진다. 세 개의 파일을 읽고, 60초가 지난 이후에 각각의 내용을 결합해서 네 번째 파일에 기록하는 노드 앱을 작성해보자.

```js
const fs = require('fs');

fs.readFile('a.txt', function(err, dataA) {
    if(err) console.error(err);
    fs.readFile('b.txt', function(err, dataB) {
        if(err) console.error(err) ;
        fs.readFile('c.txt', function(err, dataC) {
            if(err) console.error(err);
            setTimeout(function() {
                fs.writeFile('d.txt', dataA+dataB+dataC, function(err) {
                    if(err) console.error(err);
                });
        }, 1000);
    });
});
```

위 코드같이 콜백 함수가 엮이고 엮인 코드를 **콜백 헬**이라고 말한다. 위 코드에서는 에러를 기록하기만 했지만, 예외를 일으키려고 했다면 더 힘들었을 것이다.

```js
const fs = require('fs');
function readSketchyFile() {
    try {
        fs.readFile('does_not_exist.txt', function(error, data) {
            if(error) throw error;
        });
    } catch(error) {
        console.log("Error!!!!!");
    }
}

readSketchyFile();
```

위 코드는 node가 파일을 읽어들이지 못하는 예외 사항을 처리할 수 있을 것처럼 보이지만 readFile은 비동기 처리 함수이기 때문에 콜백에서 발생하는 예외사항을 잡아낼 수 없다.

그리고, 콜백이 우연히 두 번 호출되거나, 아예 호출되지 않는 경우를 방지하는 안전장치도 존재하지 않는다. 콜백이 정확히 한 번만 호출될 것을 가정하고 코드를 작성한다면 된다고 생각하고 있다면 자바스크립트는 그런 걸 보장하지 않는 다는 것을 알아둬야 한다.

이런 비동기처리를 위한 콜백을 포함한 코드가 늘어나면 늘어날수록 버그가 없고 관리하기 쉬운 코드는 작성하기 어려워진다. 그래서 이 문제를 해결하기 위해 `프로미스`가 등장하게 됐다.

이에 관한 [글](https://ruben.verborgh.org/blog/2012/12/31/asynchronous-error-handling-in-javascript/)을 읽어보는 것을 추천한다.

## 프로미스

프로미스는 콜백의 단점을 해결하기 위해 만들어졌다. 프로미스는 콜백에 비해 조금 복잡하고 귀찮게 느껴질 수 있지만, 안전하고 관리하기 쉬운 코드를 만들 수 있게 해준다.

프로미스가 콜백을 완벽하게 대체할 수 있는 상위호환의 개념은 아니다. 프로미스를 사용할 때, 프로미스 내부에서 콜백을 사용한다. 프로미스는 콜백을 관리하기 쉽게 만들어준다.

프로미스의 기본 개념은 간단하다. 프로미스 기반 비동기처리 함수를 호출하면 그 함수는 `Promise` 인스턴스 즉, `Promise` 객체를 반환한다. 프로미스는 세 가지 상태중 한 가지 상태를 가진다.

- 대기(pending): 이행되거나 거부되지 않은 초기 상태.
- 이행(fulfilled): 연산이 성공적으로 완료됨.
- 거부(rejected): 연산이 실패함.

### 대기(Pending)

대기 상태의 프로미스는 new Promise()를 호출한 상태의 프로미스를 말한다.

```js
new Promise();
```

이렇게 프로미스 인스턴스를 만들 때에 `resolve`와 `reject`를 콜백 함수의 인자로 받을 수 있다.

```js
new Promise(function(resolve, reject) {
    //codes...
});
```

### 이행(Fulfilled)

프로미스 생성자의 콜백으로 넘겨진 resolve함수가 실행됐을 때, 프로미스는 이행(fulfilled) 상태가 된다. 이행은 완료라고 생각해도 된다.

```js
new Promise(function(resolve, reject) {
    resolve();//이행.
});
```

resolve 함수에 인자를 넣으면 then메서드에 넘겨지는 콜백 함수의 인자로 받아올 수 있다. 이를 통해 콜백 함수의 결과 값을 넘길 수 있다.

```js
let myPromise = new Promise(function(resolve, reject) {
    resolve("It's success!!!");
});
myPromise.then(function(message) {
    console.log("message: " + message);
});
```

### 실패(Rejected)

프로미스 생성자의 콜백 함수에 인자로 resolve와 reject가 들어간다. 여기서 콜백 함수에서 reject함수를 실행하면 프로미스는 실패(rejected) 상태가 된다.

```js
new Promise(function(resolve, reject) {
    reject();//실패.
});
```

이행 상태에서 결과 값을 then에서 넘길 수 있었다. 실패 상태에서는 결과 값을 두 가지 방식으로 전달할 수 있다.

```js
let condition = false;
let myPromise = new Promise(function(resolve, reject) {
    if(condition) {
        resolve("It's success!!!");
    } else {
        reject("It's failed...");
    }
});
myPromise.then(function(message) {
    console.log("message: " + message);
}, function(message) {
    console.log("message: " + message);
});
```

reject의 인자는 then 메서드의 두 번째 콜백 함수로 받을 수 있고

```js
myPromise.catch(function(message) {
    console.log("message: " + message);
});
```

catch 메서드의 콜백 함수로도 받을 수 있다.

프로미스는 객체이므로 어디든 전달할 수 있다. 비동기적 처리를 프로미스를 선언한 곳에서 하지 않고 다른 함수에서 처리하고 싶다면 프로미스를 넘기기만 하면 된다. 

## 프로미스 만들기

프로미스를 만드는 것은 어렵지 않다. `resolve`(성공)와 `reject`(실패) 콜백이 있는 함수로 `Promise` 인스턴스를 만들기만 하면 된다. 위에서 만들었던 countdown 함수를 프로미스를 사용해서 고쳐보자. 매개변수를 받아서 몇 초 카운트다운을 할 지 전달받고, 카운트다운이 끝나면 프로미스를 반환하게 만들어보자.

```js
function countdown(seconds) {
    return new Promise(function(resolve, reject) {
        for(let i = seconds; i>=0; i--) {
            setTimeout(function() {
                if(i>0) console.log(i);
                else resolve(console.log("Go!"));
            }, (seconds-i)*1000);
        }
    });
}
```

위 코드는 썩 좋은 함수는 아니다. 코드가 너무 장황하고, 콘솔을 쓰지 않기를 원할 수도 있다. 또 웹 페이지에 카운트다운이 끝나면 페이지 요소를 업데이트하는 목적에 쓰기도 좋지 않아 보인다. 하지만 위 코드에는 프로미스를 어떻게 쓰는지 잘 드러나 있다. `resolv`e와 `reject`는 함수다. 코드를 보면 `resolve`를 여러 번 호출하면 프로미스를 여러 개 만들 수 있을 것 같다는 생각이 들 수 있지만. `resolve`와 `reject`는 첫 번째 호출한 것만 의미가 있다. 프로미스는 성공이나 실패만을 나타낼 수 있다.

## 프로미스 사용

countdown 함수를 사용하는 방법을 알아보자. 프로미스는 무시하고 countdown(1)처럼 그냥 countdown 함수를 호출하면 된다. 하지만 프로미스의 장점을 온전히 사용하려면 함수를 실행했을 때 반환되는 Promise 인스턴스를 사용할 줄 알아야한다.

```js
countdown(5).then(
    function() {
        console.log("countdown completed");
    }.
    function(err) {
        console.log("countdown got error" + err.message);
    }
);
```

위 예제에서는 countdown 함수를 실행했을 때 반환되는 프로미스를 변수에 할당하지 않고 바로 then 핸들러를 바로 호출했다. then 핸들러는 성공 콜백과 에러 콜백을 받는다. 경우의 수는 **성공** 혹은 **실패** 이 두 가지뿐이다. 프로미스는 catch 핸들러도 지원하기 때문에 핸들러를 둘로 나눠서 사용해도 된다.

```js
const p = countdown(5);// 이 때 countdown이 실행된다.

p.then(function() {
    console.log("countdown completed");\
});
p.catch(function() {
    console.log("countdown got error" + err.message);
});
```

그렇다면 countdown 함수에서 에러가 발생하게 만들어보자.

```js
function countdown(seconds) {
    return new Promise(function(resolve, reject) {
        for(let i = seconds; i>=0; i--) {
            setTimeout(function() {
                if(i===10) return reject(new Error("Big Error!!!"));
                if(i>0) console.log(i);
                else resolve(console.log("Go!"));
            }, (seconds-i)*1000);
        }
    });
}
```

이제 countdown 함수에서 10을 카운트하면 에러가 발생하게 된다. 하지만 에러가 발생해도 함수는 멈추지 않는다. reject나 resolve는 함수를 멈추진 않는다. 이 함수들은 그저 프로미스의 상태를 관리할 뿐이다.

## 이벤트

이벤트는 자바스크립트에서 자주 사용된다. 이벤트가 일어남녀 이벤트 발생을 담당하는 개체(emitter)에서 이벤트가 일어났음을 알린다. 필요한 이벤트는 모두 주시(listen)할 수 있다. 이벤트는 어떻게 주시할까? 당연히 `콜백`을 통해서 주시한다. 노드에는 이벤트를 지원하는 모듈 EventEmitter가 내장되어 있다. EventEmitter는 countdown 같은 함수와 함께 사용해도 되지만, 원래는 클래스와 함께 사용하도록 설계됐다. 그러면 countdown 함수를 클래스로 바꿔보자.

```js
const EventEmitter = require('events').EventEmitter;

class CountDown extends EventEmitter {
    constructor(sec, superstition) {
        super();
        this.sec = sec;
        this.superstition = superstition;
    }

    go() {
        const countdown = this;
        return new Promise(function(resolve, reject) {
            for(let i = countdown.sec; i>=0; i--) {
                setTimeout(function() {
                    if(this.superstition && i === 3)
                        return reject(new Error("Errrr!"));
                    countdown.emit('tick',i);
                    if(i === 0) resolve();
                }, (countdown.sec - i) * 1000)
            }
        });
    }
}
```

EventEmitter를 상속받는 클래스는 이벤트를 발생시킬 수 있다. 위 클래스에서 실제로 카운트다운을 작동시키는 부분은 go 메서드다. go 메서드에서 가장 먼저 한 일은 this를 countdown에 할당한 것이다. 콜백 함수에서 this는 클래스의 인스턴스가 아닌 다른 것을 가리키게 된다. 따라서 this를 다른 변수에 저장해야 콜백 함수안에서 사용할 수 있다.

가장 중요한 부분은 countdown.emit('tick',i)이다. 이 부분에서 tick 이벤트를 발생시키고, 필요하다면 프로그램의 다른 부분에서 이 이벤트를 주시할 수 있다. 개선한 카운트다운은 아래 코드처럼 사용할 수 있다.

```js
const c = new CountDown(5);
c.on('tick', function(i) {
    if(i>0) console.log(i);
});

c.go()
  .then(function() {
      console.log('Go');
  })
  .catch(function(err) {
      console.error(err.message);
  })
```

위 코드는 EventEmitter의 on 메서드가 이벤트를 주시하는 부분이다. 이 예제에서는 tick 이벤트에 콜백을 등록했다. i가 0보다 클 때 출력하고 카운트 다운이 끝나면 Go를 출력한다.

하지만 아직 문제가 있다. 바로 에러가 발생했을 때 프로미스가 실패 상태가 됐지만 카운트다운이 지속된다는 점이다. 이 문제를 해결하기 위해서는 더 진행할 수 없다는(에러가 발생했다는) 사실을 알았을 때, 대기 중인 타임아웃을 모두 취소하는 것이다. 

```js
class CountDown extends EventEmitter {
    constructor(sec, superstitious) {
        super();
        this.sec = sec;
        this.superstitious = !!superstitious;
    }

    go() {
        const countdown = this;
        const timeoutIds = [];
        return new Promise(function(resolve, reject) {
            for(let i = countdown.sec; i>=0; i--) {
                timeoutIds.push(setTimeout(function() {
                    if(countdown.superstitious && i === 3) {
                        timeoutIds.forEach(clearTimeout);
                        return reject(new Error("Errrr!"));
                    }
                    countdown.emit('tick',i);
                    if(i === 0) resolve();
                }, (countdown.sec - i) * 1000));
            }
        });
    }
}
```

CountDown 클래스를 위처럼 바꾸면 i값이 3이 될 때 대기 중인 타임아웃이 모두 종료된다.

## 프로미스 체인

앞에서 콜백 헬이 생기는 이유는 한 번에 여러가지 비동기 작업을 처리하기 때문이었다. 프로미스는 이런 콜백 헬을 해결하기 위해서 나왔는데 여러 개의 프로미스를 한꺼번에 처리하기 위한 문법이 프로미스 체인이다. 위에서 콜백 헬 예시를 프로미스로 예쁘게 만들어보자.

```js
const fs = require('fs');

function readA() {
let data = "";
return new Promise(function(resolve, reject) {
    fs.readFile('a.txt', function(err, dataA) {
        if(err) reject(new Error("error!"));
        data += dataA;
        resolve(data);
    });
});
}

function readB(data) {
return new Promise(function(resolve, reject) {
    fs.readFile('b.txt', function(err, dataB) {
        if(err) reject(new Error("error!"));
        data += dataB;
        resolve(data);
    });
});
}

function readC(data) {
return new Promise(function(resolve, reject) {
    fs.readFile('c.txt', function(err, dataC) {
        if(err) reject(new Error("error!"));
        data += dataC;
        resolve(data);
    });
});
}

function writeD(data) {
return new Promise(function(resolve, reject) {
    fs.writeFile('d.txt', data, function(err) {
        if(err) console.error(err);
    });
});
}

readA()
  .then(readB)
  .then(readC)
  .then(writeD)
  .catch(function(error) {
    console.log(error);
  });// 프로미스 체인
```

프로미스는 위처럼 연결해서 사용할 수 있다. catch 메서드가 맨 밑에 있지만 어떤 콜백 함수에서 에러가 발생해도 에러를 잡아낼 수 있다.